timeout: 10
verbose: yes

wallpaper: boot():/background.bmp
interface_branding: AaronOS
interface_branding_colour: 00ddaa
term_font: boot():/boot/limine.fnt

/Try/Install AaronOS
    protocol: multiboot2
    kernel_path: boot():/boot/kernel.elf

/Boot Hard Disk
    protocol: bios
    drive: 1

/Boot from USB
    protocol: bios
    drive: 2

/Boot from CD/DVD
    protocol: bios

/Shutdown
