timeout: 10
verbose: yes

wallpaper: boot():/overlay.bmp
interface_branding: AaronOS
interface_branding_colour: 00ddaa
term_font: boot():/boot/limine.fnt

/AaronOS
    comment: Install or Try AaronOS with this option.
    protocol: multiboot2
    kernel_path: boot():/BOOT/KERNEL.ELF

/Boot from USB
    comment: Boot from a USB stick.
    protocol: bios
    drive: 2

/Boot from CD/DVD
    comment: Boot from a CD/DVD.
    protocol: bios

/Shutdown
    comment: Do not select this option. To shutdown, please press F2. To reboot, press F1.