timeout: 10
verbose: yes

wallpaper: boot():/overlay.bmp
interface_branding: AaronOS
interface_branding_colour: 00ddaa
term_font: boot():/boot/limine.fnt

/Try/Install AaronOS
    comment: Try or Install AaronOS
    protocol: multiboot2
    kernel_path: boot():/boot/kernel.elf

/Boot Hard Disk
    comment: Boot from your Hard Disk.
    protocol: bios
    drive: 0

/Boot from USB
    comment: Boot from a USB stick.
    protocol: bios
    drive: 2

    
/Shutdown
    comment: Do not select this option. To shutdown, please press F2. To reboot, press F1.
