# Wait 5 seconds before booting the default entry
TIMEOUT=5

# The name displayed in the Limine boot menu
:AaronOS
    # Tells Limine to use the Multiboot2 specification
    PROTOCOL=multiboot2
    
    # Points to your kernel location relative to the boot partition
    KERNEL_PATH=boot():/boot/kernel.elf
